# This file was generated by GoReleaser. DO NOT EDIT.
cask "memex" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "15488edfb50b08e4352e3046f0967077029933f4590b950b99a45a7ce9f8b401"
      url "https://github.com/alessandrotesoro/memex/releases/download/v#{version}/memex_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e95b23f858e4c20cdf4fb2bbe86d66536c6ce95d7441cdc92e4ac64ebef323db"
      url "https://github.com/alessandrotesoro/memex/releases/download/v#{version}/memex_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f4d1253376543178589630558d437e14be5aeed15c094738a5a738fd2cc226ee"
      url "https://github.com/alessandrotesoro/memex/releases/download/v#{version}/memex_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "46e8dc53296ab4c944676470125712d9d13124605832a8af0bd59017663d8861"
      url "https://github.com/alessandrotesoro/memex/releases/download/v#{version}/memex_#{version}_linux_arm64.tar.gz"
    end
  end

  name "memex"
  desc "Per-project hybrid code + docs search for Claude Code"
  homepage "https://github.com/alessandrotesoro/memex"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "memex"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/memex"]
    end
  end

  # No zap stanza required

end
